local color = require "color"

local frames = {}
local activeFrame
local currentFrame = 1
local second = os.clock()

-- Load some default values for our rectangle.
function love.load()
    --physic objects
    love.physics.setMeter(64)
    world = love.physics.newWorld(0, 9.81*64, true)

    objects = {}

    objects.ground = {}
    objects.ground.body = love.physics.newBody(world, love.graphics.getWidth()/2, love.graphics.getHeight()-1 /2)
    objects.ground.shape = love.physics.newRectangleShape(love.graphics.getWidth(), 50)
    objects.ground.fixture = love.physics.newFixture(objects.ground.body, objects.ground.shape)

    objects.ball = {}
    objects.ball.body = love.physics.newBody(world, love.graphics.getWidth()/2, love.graphics.getHeight()/2, "dynamic")
    objects.ball.shape = love.physics.newCircleShape(20)
    objects.ball.fixture = love.physics.newFixture(objects.ball.body, objects.ball.shape, 1)
    objects.ball.fixture:setRestitution(0.2)

    objects.leftWall = {}
    objects.leftWall.body = love.physics.newBody(world, 0, love.graphics.getHeight()-1/2)
    objects.leftWall.shape = love.physics.newRectangleShape(0, 0, 0, love.graphics.getHeight()*2)
    objects.leftWall.fixture = love.physics.newFixture(objects.leftWall.body, objects.leftWall.shape)

    objects.rightWall = {}
    objects.rightWall.body = love.physics.newBody(world, 5, love.graphics.getHeight()-1/2)
    objects.rightWall.shape = love.physics.newRectangleShape(love.graphics.getWidth(), 0, 10, love.graphics.getHeight()*2)
    objects.rightWall.fixture = love.physics.newFixture(objects.rightWall.body, objects.rightWall.shape)

    objects.ceiling = {}
    objects.ceiling.body = love.physics.newBody(world, love.graphics.getWidth()/2, 0)
    objects.ceiling.shape = love.physics.newRectangleShape(love.graphics.getWidth()/2, 0, love.graphics.getWidth()*2, 0)
    objects.ceiling.fixture = love.physics.newFixture(objects.ceiling.body, objects.ceiling.shape)
    print(love.graphics.getHeight())

    --sprite load
    imageFile = love.graphics.newImage("assets/assets_v2.png")
    frames[1] = love.graphics.newQuad(0,0,48,48,imageFile:getDimensions())
    activeFrame = frames[currentFrame]

    love.graphics.setBackgroundColor(color.hex("#57a2f7"))
    love.window.setMode(800, 650)
end

local jump = false
-- Increase the size of the rectangle every frame.
function love.update(dt)
  world:update(dt)
  print(objects.ball.body:getLinearVelocity())
  -- here we are going to create some keyboard events
  -- press the right arrow key to push the ball to the right
  if love.keyboard.isDown("right") then
    objects.ball.body:applyForce(400, 0)
  -- press the left arrow key to push the ball to the left
  elseif love.keyboard.isDown("left") then
    objects.ball.body:applyForce(-400, 0)
  -- press the up arrow key to set the ball in the air
  elseif love.keyboard.isDown("up") then
    local x, y = objects.ball.body:getLinearVelocity()
    if(y > -300 and not jump) then
      objects.ball.body:applyForce(0, -11500)
      jump = true
    elseif (y == 0) then
      jump = false
    end
  elseif love.keyboard.isDown("down") then
    objects.ball.body:applyForce(0, 1500)

  elseif love.keyboard.isDown("r") then
    objects.ball.body:setPosition(love.graphics.getWidth()/2, love.graphics.getWidth()/2)
    -- we must set the velocity to zero to prevent a potentially large
    -- velocity generated by the change in position
    objects.ball.body:setLinearVelocity(0, 0)
  end
end

-- Draw a coloured rectangle.
function love.draw()
    -- no color graphics
    love.graphics.polygon("fill", objects.leftWall.body:getWorldPoints(objects.leftWall.shape:getPoints()))
    love.graphics.polygon("fill", objects.rightWall.body:getWorldPoints(objects.rightWall.shape:getPoints()))
    love.graphics.polygon("fill", objects.ceiling.body:getWorldPoints(objects.ceiling.shape:getPoints()))

    -- color graphics
    love.graphics.setColor(color.hex("#57a2f7"))
    love.graphics.polygon("line", objects.ground.body:getWorldPoints(objects.ground.shape:getPoints()))

    love.graphics.setColor(color.hex("#8c0808"))
    love.graphics.circle("fill", objects.ball.body:getX(), objects.ball.body:getY(), objects.ball.shape:getRadius())

    love.graphics.setColor(color.hex("#FFFFFFFF"))
    for i = 0, love.graphics.getWidth(), 48 do
      love.graphics.draw(imageFile, activeFrame, i, love.graphics.getHeight()-150/2)
    end
  end